config/routes.rb
Rails.application.routes.draw do
  get 'profile/show'



  devise_for :users

  namespace :dutchies do
    resources :offers, only: [:index] do
      member do
        patch :accept
        patch :refuse
      end
    end
  end

  resources :dutchies, only: [:index, :show] do
    resources :offers, only: [:new, :create]
  end

  resources :profile, only: [:show, :edit, :update]


  namespace :refugees do
    resources :requests, only: [:index]
  end

  resources :refugees, only: :show

# resources :requests, only: [:index]
#   resources :offers, only: [:index] do
#       member do
#         patch :accept
#         patch :refuse
#       end
#     end



  root to: 'pages#home'

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :refugee, class_name: 'User', foreign_key: :refugee_id
  belongs_to :dutchy, class_name: 'User', foreign_key: :dutchy_id

  validates :message, presence: true
  validates :status, :inclusion => {in: ["pending", "declined", "accepted"]}
  validates :refugee_id, :dutchy_id, presence: true
  validates :dutchy_id, uniqueness: {scope: :refugee_id, message: "You've already sent this Dutchie a request."}
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  has_many :requests, class_name: 'Request', foreign_key: :refugee_id
  has_many :offers, class_name: 'Request', foreign_key: :dutchie_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :kind, :inclusion => {in: ["dutchie", "refugee"]}
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :description, :kind, :photo, :photo_cache])
  end


end

app/controllers/dutchies/offers_controller.rb
class Dutchies::OffersController < ApplicationController
  before_action :find_user, only: :index

  def index
    @offers = Request.where(dutchy_id: current_user[:id])
  end

  def accept
    @offer = Request.find(params[:id])
    @offer.update(status: "accepted")
    redirect_to dutchies_offers_path
  end

  def refuse
    @offer = Request.find(params[:id])
    @offer.update(status: "refused")
    redirect_to dutchies_offers_path
  end

  private

  def find_user
    @user = User.find(current_user[:id]) if current_user
  end


end

app/controllers/dutchies_controller.rb
class DutchiesController < ApplicationController
  before_action :find_user, only: :show

  def index
    @dutchies = User.where(kind: "dutchie")
  end

  def show
    @dutchie = User.find(params[:id])
  end


  private
  def find_user
    @user = User.find(current_user[:id]) if current_user
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :find_dutchie, only: [:new, :create]
  before_action :find_user, only: [:new, :create]

  def new
    @offer = Request.new
  end

  def create
    @offer = Request.new(offer_params)
    @offer.dutchy_id = params[:dutchy_id]
    @offer.refugee_id = current_user[:id]
    @offer.status = "pending"
    if  @offer.save
      redirect_to refugees_requests_path()
    else
      render :new
    end
  end


  private

  def find_dutchie
    @dutchie = User.find(params[:dutchy_id])
  end

   def find_user
    @user = User.find(current_user[:id]) if current_user
  end

  def offer_params
    params.require(:request).permit(:message)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @dutchies = User.where(kind: "dutchie")
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path(current_user[:id])
    else
      render "edit"
    end
  end


  private
  def find_user
    @user = User.find(current_user[:id]) if current_user
  end

  def user_params
    params.require(:user).permit(:id, :email, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :created_at, :updated_at, :kind, :username, :photo, :photo_cache, :description)
  end
end

app/controllers/refugees/requests_controller.rb
class Refugees::RequestsController < ApplicationController
  before_action :find_user, only: :index

  def index
      @requests = @user.requests.reverse
  end

  private

  def find_user
    @user = User.find(current_user[:id]) if current_user
  end
end

app/controllers/refugees_controller.rb
class RefugeesController < ApplicationController
  before_action :find_user, only: :show

  def show
    @refugee = User.find(params[:id])
    @offer = Request.find_by(dutchy_id: @user.id, refugee_id: @refugee.id)
  end

  private

  def find_user
    @user = User.find(current_user[:id]) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dutchies_helper.rb
module DutchiesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/refugees_helper.rb
module RefugeesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/dutchies/index.html.erb
<div class="wrapper">
  <div class="dutchie-title">
    <h1>DUTCHIES</h1>
    <p>Here is a list of all Dutchies waiting to share their Dutch with you!</p>
  </div>

  <div class="container">
    <div class="row">
      <% @dutchies.each do |dutchie| %>
      <div class="col-xs-12 col-sm-6">
        <div class= "card">
          <div class= 'card-photo'>
            <%= image_tag(dutchie.photo, class: 'avatar-large')  %>
          </div>
          <div>
            <div class='card-name'>
              <%= dutchie.username %>
            </div>
            <div class="card-description">
              <%= dutchie.description %>
            </div>
          </div>
          <div>
            <%= link_to "", dutchy_path(dutchie), class: 'card-link'  %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>




 <!--  <% @dutchies.each do |dutchie| %>
 <img src="<%= dutchie.photo %>" alt="<%=dutchie.username%>">  <br>
 <%= dutchie.username %> <br>
 <%= dutchie.description %> <br>
 <%= link_to "Go to this profile", dutchy_path(dutchie)  %> <br>
 <hr>
 <% end %> -->
</div>

app/views/dutchies/offers/index.html.erb
<div class="wrapper">
  <p class="text-center requests">Hi, <%= @user.username %> here are the requests you got</p>


  <% @offers.each do |offer| %>
  <div class="card-request">
    <div class="left">
      <div>
        <img src=" <%=  offer.refugee.photo %>" alt=" <%= offer.refugee.username %>  " class="avatar-large"> </div> <br>
        <%= offer.refugee.username %> <br>
      </div>
      <div right>
        <div class="message-a">
          <%=offer.message  %>
        </div> <br>
        <%= link_to "Go to the profile page of #{offer.refugee.username}", refugee_path(offer.refugee)  %> <br>

        <!-- Show button to accept or decline if status is pending  -->
        <% if offer.status == "pending" %>
        <%= link_to "ACCEPT", accept_dutchies_offer_path(offer), method: :patch , class:"btn btn-success" %>
        <%= link_to "REFUSE", refuse_dutchies_offer_path(offer), method: :patch , class:"btn btn-danger" %>

        <!-- Show email of refugee if accepted -->
        <% elsif offer.status == "accepted" %>
        You accepted, sent <%= offer.refugee.username  %> an <a href="mailto:<%= offer.refugee.email %>"> email</a>
        <!-- Show declinemessage if declined -->
        <% else %>
        You declined the offer of <%= offer.refugee.username %>
        <% end %>
      </div>
    </div>

  </div>
  <% end %>




</div>

app/views/dutchies/show.html.erb
<div class="wrapper">

  <div class= "card">
    <div class= 'card-photo'>
    <%= image_tag(@dutchie.photo, class: 'avatar-large')  %>
    </div>
    <div>
      <div class='card-name'>
        <%= @dutchie.username %>
      </div>
      <div class="card-description">
        <%= @dutchie.description %>
      </div>
    </div>
    <div>
      <% if @user != nil %>
      <% if @user.kind == "refugee" %>
      <%= link_to "Send a Request", new_dutchy_offer_path(@dutchie), class:"btn btn-info" %>
      <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Refutalk</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/offers/new.html.erb
<div class="wrapper">
  <div class="wraprequest">
 <div class="conversation">
 <div class="sender">
 <img src=" <%= @user.photo %> " class="avatar-large"> <br>
 <%= @user.username %>
  </div>
  <fa class="fa fa-arrows-h"></fa>
  <div class="receiver">
  <img src=" <%=  @dutchie.photo %> " class="avatar-large"> <br>
  <%= @dutchie.username %>
  </div>
 </div>
<div class="flexxr">
  <div class="newrequest">
    <% if @offer.errors.any? %>
    <div class="alert alert-warning alert-request"> <%= @offer.errors.messages.first[1].join %> </div>
    <% end %>
    <%= form_for [@dutchie, @offer], url: dutchy_offers_path do |f| %>
    <%= f.text_area :message ,:class => 'message' %>
    <%= f.submit :class => 'btn btn-success' %>
    <% end %>
  </div>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="wrapper banner">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class= title>
        <%= image_tag "logowithtext.png", class: "banner-logo" %>

          <!-- <h1 class= text-center >Refugee talk</h1> -->
        </div>
        <div class="connect text-center">
          <h2>CONNECT</h2> <br>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras euismod sapien lacus, varius suscipit orci
          posuere vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
          Phasellus sit amet feugiat augue. Donec turpis sapien, sagittis sit amet mattis id, interdum sit amet lectus.
          Pellentesque venenatis lectus leo, id porttitor erat feugiat et. Nullam auctor leo eu nibh pulvinar euismod. Etiam iaculis varius
          ultrices. Nulla bibendum mauris quis velit finibus, sed venenatis.
        </div>
        <div class="button-center">
          <% if signed_in? %>
          <% else %>
          <%= link_to(new_user_registration_path) do  %>
          <div class="btn sign-in-button">
            SIGN UP
          </div>
          <% end  %>
          <% end %>
        </div>
        </div>
        </div>
        </div>
        </div>
        <div class="wrapper">
        <div class="dutchy-list">


          <div class="dutchies">

            <div class="container">
            <h2 class="text-center">
            THE DUTCHIES
          </h2> <br>
              <div class="row">
                <% @dutchies.first(6).each do |dutchie| %>
                <div class="col-xs-12 col-md-6">
                  <div class= "card">
                    <div class= 'card-photo'>
                      <%= image_tag(dutchie.photo, class: 'avatar-large')  %>
                    </div>
                    <div class = card-text>
                      <div class='card-name'>
                        <%= dutchie.username %>
                      </div>
                      <div class="card-description">
                        <%= dutchie.description %>
                      </div>
                    </div>
                    <div>
                      <%= link_to "", dutchy_path(dutchie), class: 'card-link'  %>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div style="text-align:center">

        <%=link_to "ALL DUTCHIES", dutchies_path, class:"btn dutchy-button" %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/refugees/requests/index.html.erb
<div class="wrapper">
Hi <%= @user.username %> <br>
here are the requests you've send</p>

<div class="wrapper-request">

<% @requests.each do |request| %>
<div class="card-request">
  <div class="left">
  <div>
  <img src=" <%=  request.dutchy.photo %>" alt=" <%= request.dutchy.username %>  " class="avatar-large"> </div>
  <div>
  <span class="name text-center"><%= request.dutchy.username %> </span> </div>
  </div>

  <div class="right">
  <div class="message-a"><%= request.message %></div>
 <br>

<% if request.status == "pending"%>
  <%= request.dutchy.username  %> has not responded yet.
<% elsif request.status == "declined" %>
  <%= request.dutchy.username  %> declined your request.
<% elsif request.status == "accepted" %>
  Send an email to <a href="mailto:<%= request.dutchy.email %>"><%= request.dutchy.username  %></a>
<% end %> <br>
  <%= link_to "Go to the profile page of #{request.dutchy.username}", dutchy_path(request.dutchy)  %>

  </div>
  </div>

<% end %>
</div>

app/views/refugees/show.html.erb
<div class="wrapper">
  <img src="<%= @refugee.photo %>" alt="">
  <h1> <%= @refugee.username %></h1>
  <p><%= @refugee.description %></p>


  <!-- Show button to accept or decline if status is pending  -->
  <% if @offer %>
  <% if @offer.status == "pending" %>
  <%= link_to "ACCEPT", accept_dutchies_offer_path(@offer), method: :patch , class:"btn btn-success" %>
  <%= link_to "REFUSE", refuse_dutchies_offer_path(@offer), method: :patch , class:"btn btn-danger" %>

  <!-- Show email of refugee if accepted -->
  <% elsif @offer.status == "accepted" %>
  You accepted, sent <%= @offer.refugee.username  %> an <a href="mailto:<%= @offer.refugee.email %>"> email</a>
  <!-- Show declinemessage if declined -->
  <% else %>
    You declined the offer of <%= @offer.refugee.username %>
  <% end %>
  <% end %>
  <hr>
  <%= link_to "Back to my requests", dutchies_offers_path %>
</div>

app/views/requests/index.html.erb
<h1>THIS ARE YOUR REQUESTS</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%#= "RT" %> <img src="/assets/logowithouttext.png" alt="">
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <!-- Notification -->
    <% if current_user.kind == "dutchie" %>
    <%= link_to dutchies_offers_path , class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-comment"></i>
      <div class="badge badge-blue"><%= Request.where(dutchy_id: current_user[:id]).size  %>

      </div>

    </div>
    <% end  %>
    <% else %>
    <%= link_to refugees_requests_path , class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-comment"></i>
      <div class="badge badge-blue"><%= current_user.requests.length  %></div>
    </div>
    <% end %>
    <% end  %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= link_to current_user.username, "#", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Button (call-to-action) -->
    <%= link_to (new_user_session_path) do %>
    <div class="navbar-wagon-item navbar-wagon-button btn">
      <i class="fa fa-plug" aria-hidden="true"></i>
      LOGIN
    </div>

    <% end  %>

    <% end %>
  </div>
</div>